title: Who am I docs
description: The projects documentation with usage instructions.
remote_theme: just-the-docs/just-the-docs@v0.8.1

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
